load('/mnt/c/Users/unicornt/Desktop/0/pj/CodeAlchemist/bin/jsLib/V8.js');
load('sort-base.js');
codealchemist_log_type_pre('-7439138647391350337', ({v1 : ((typeof CreateSortFn) != ('undefined')) ? (CreateSortFn) : (undefined)}));
let sortfn = CreateSortFn([]);
codealchemist_log_type_post('-7439138647391350337', ({v1 : ((typeof CreateSortFn) != ('undefined')) ? (CreateSortFn) : (undefined), v0 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-8178944912322476626', ({v2 : ((typeof CreatePackedSmiArray) != ('undefined')) ? (CreatePackedSmiArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('PackedSmi', 1000, sortfn, CreatePackedSmiArray);
codealchemist_log_type_post('-8178944912322476626', ({v2 : ((typeof CreatePackedSmiArray) != ('undefined')) ? (CreatePackedSmiArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-3917306039692677161', ({v2 : ((typeof CreatePackedDoubleArray) != ('undefined')) ? (CreatePackedDoubleArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('PackedDouble', 1000, sortfn, CreatePackedDoubleArray);
codealchemist_log_type_post('-3917306039692677161', ({v2 : ((typeof CreatePackedDoubleArray) != ('undefined')) ? (CreatePackedDoubleArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-1221193483583505138', ({v2 : ((typeof CreatePackedObjectArray) != ('undefined')) ? (CreatePackedObjectArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('PackedElement', 1000, sortfn, CreatePackedObjectArray);
codealchemist_log_type_post('-1221193483583505138', ({v2 : ((typeof CreatePackedObjectArray) != ('undefined')) ? (CreatePackedObjectArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('9023223086753892272', ({v2 : ((typeof CreateHoleySmiArray) != ('undefined')) ? (CreateHoleySmiArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('HoleySmi', 1000, sortfn, CreateHoleySmiArray);
codealchemist_log_type_post('9023223086753892272', ({v2 : ((typeof CreateHoleySmiArray) != ('undefined')) ? (CreateHoleySmiArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-839153461950627522', ({v2 : ((typeof CreateHoleyDoubleArray) != ('undefined')) ? (CreateHoleyDoubleArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('HoleyDouble', 1000, sortfn, CreateHoleyDoubleArray);
codealchemist_log_type_post('-839153461950627522', ({v2 : ((typeof CreateHoleyDoubleArray) != ('undefined')) ? (CreateHoleyDoubleArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-8304443609569723461', ({v2 : ((typeof CreateHoleyObjectArray) != ('undefined')) ? (CreateHoleyObjectArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('HoleyElement', 1000, sortfn, CreateHoleyObjectArray);
codealchemist_log_type_post('-8304443609569723461', ({v2 : ((typeof CreateHoleyObjectArray) != ('undefined')) ? (CreateHoleyObjectArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
codealchemist_log_type_pre('-7424668152238533652', ({v2 : ((typeof CreateDictionaryArray) != ('undefined')) ? (CreateDictionaryArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
createSortSuite('Dictionary', 1000, sortfn, CreateDictionaryArray);
codealchemist_log_type_post('-7424668152238533652', ({v2 : ((typeof CreateDictionaryArray) != ('undefined')) ? (CreateDictionaryArray) : (undefined), v0 : ((typeof createSortSuite) != ('undefined')) ? (createSortSuite) : (undefined), v1 : ((typeof sortfn) != ('undefined')) ? (sortfn) : (undefined)}));
